services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: proxy
    ports:
      - "54320:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d proxy"]
      interval: 5s
      timeout: 5s
      retries: 10
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: /app
      DATABASE_URL: postgresql+psycopg2://postgres:qwerty@db:5432/proxy
    depends_on:
      - db
volumes:
  postgres_data: